
$(function() {

    // Populate using an object literal

    WTF.init({

        heading: [
            "Why don't you fucking research",
            "Your next fucking experiment should look at",
            "How about you fucking investigate",
            "Go fucking study"
        ],
        response: [
            "➜ Already fucking done",
            "➜ Give me a-fucking-nother one",
            "➜ Next fucking experiment",
            "➜ Nobody fucking cares",
            "➜ That's fucking unethical",
            "➜ Not fucking possible",
            "➜ Too fucking difficult",
            "➜ No fucking money in this area"
        ],
        template: [
            "The difference in @depvar between @compare",
            "The impact of @invar on the @depvar of @group",
            "The effects of @invar on the @depvar of @group",
            "The influence of @invar on the @depvar of @group",
            "The correlation between @invar and @depvar in @group",
            "The association between @invar and @depvar in @group",
            "The relation between @invar and @depvar in @group",
            "The relationship between @invar and @depvar in @group"
        ],
        invar: [
            "alcohol consumption",
            "daily Twitter use",
            "LSD",
            "Cannabis",
            "drugs",
            "meditation",
            "swearing",
            "sleep deprivation",
            "exercise",
            "some kind of brain lesion",
            "naps",
            "smoking",
            "coffee",
            "Virtual Reality",
            "salary",
            "sexting",
            "fake news",
            "classical music",
            "video games",
            "punishments / rewards",
            "age",
            "working memory training",
            "spatial cues",
            "spaced vs massed learning",
            "presentation rate",
            "gambling addiction",
            "linguistic cues",
            "colors",
            "daily social media use",
            "practice",
            "experience"
        ],
        depvar: [
            "social development",
            "intelligence",
            "creativity",
            "attention span",
            "emotional intelligence",
            "spatial perception",
            "depression",
            "anxiety",
            "stress",
            "dreams",
            "language development",
            "language comprehension",
            "color perception",
            "problem solving",
            "critical thinking",
            "mood",
            "mental imagery",
            "long-term memory",
            "working memory",
            "memory span",
            "selective inhibition",
            "learning speed",
            "decision making",
            "morality",
            "personality traits",
            "persuasion",
            "confidence",
            "work performance",
            "motivation",
            "attraction",
            "arousal",
            "spider phobia",
            "empathy",
            "memory suppression",
            "semantic memory",
            "white matter volume",
            "gray matter volume",
            "cortical complexity",
            "false memories",
            "action comprehension",
            "gestures",
            "language lateralization",
            "handedness",
            "object recognition",
            "pattern recognition",
            "time sensation"
        ],
        group: [
            "children",
            "teenagers",
            "elderly",
            "men and women",
            "students",
            "Alzheimer patients",
            "adults",
            "criminals",
            "pet owners",
            "taxi drivers",
            "healthy humans",
            "psychologists",
            "daily Twitter users",
            "millionaires",
            "extroverts",
            "introverts",
            "anxious people",
            "politicians",
            "ADHD adults",
            "optimists",
            "pessimists"
        ],
        compare: [
            "Western and Eastern people",
            "humans and chimpanzees",
            "individualistic and collectivist cultures",
            "extroverts and introverts",
            "people from the US and UK",
            "adults with and without social anxiety",
            "optimists and pessimists",
            "children and adults",
            "men and women"
        ]
    });

}); 
